spring.application.name=auth-service

#Changing the default server port to 5050
server.port=5050

#JDBC Connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/athidhi_gruha
spring.datasource.username=Athidhi
spring.datasource.password=Athidhi

spring.jpa.hibernate.ddl-auto=update

#Few formatting properties
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Custom Configurations
jwt.secret=MySuperSecureJwtSecretKeyForAthidhiGruhaProject12345
jwt.expiry=3600000
athidhi.logging.request-cache-size=1048576
athidhi.logging.duration.threashold.slowRequest=500
athidhi.logging.duration.threashold.criticalRequest=1000