spring.application.name=frontend-ui

#Changing the server default Port from 8080 to 4040
server.port=4040

#adding the properties
spring.thymeleaf.cache=false

#
# JDBC properties
#
spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.jpa.hibernate.ddl-auto=update

#disbaling the basic spring security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
